### ISSUE TITLE
Error loading import source

### ISSUE THREAD

**Issue by topchyan** [syntithenai/abc2book#1]
I have downloaded and trying to run this from the index.html in the browser (Firefox). 
Initially the page looks like this:

![image](https://github.com/syntithenai/abc2book/assets/16518288/79591858-d948-4228-99f8-ce480cc1a177)

When I click on any button I get the error

![image](https://github.com/syntithenai/abc2book/assets/16518288/002a6478-075e-4b6d-ae59-5d5896ce6caa)

What am I doing wrong?

**Comment by syntithenai** [comment]
The resource files are served by an additional server in development.

As well as
`npm start
`
In a different terminal
`npm run serveextras
`
